// SPDX-License-Identifier: Apache-2.0

package nutanix

import (
	"fmt"
	"math"
	"os"
	"strings"

	"github.com/zyvorai/transiva/manifest"
)

// BuildArtifactManifest creates a h2kvm Artifact Manifest v1.0 from converted disks.
func BuildArtifactManifest(vm PickupVM, disks []ConvertedDisk, format string) (*manifest.ArtifactManifest, error) {
	if len(disks) == 0 {
		return nil, fmt.Errorf("no disks to include in manifest")
	}
	if format == "" {
		format = "qcow2"
	}

	memGB := int(math.Round(vm.MemoryGiB))
	if memGB == 0 && vm.MemoryGiB > 0 {
		memGB = 1
	}

	cluster := vm.ClusterName
	if cluster == "" {
		cluster = vm.ClusterUUID
	}

	builder := manifest.NewBuilder().
		WithSource("nutanix", vm.UUID, vm.Name, cluster, "nutanix-nfs-pickup").
		WithVM(vm.VCPUs, memGB, "bios", "unknown", "", false)

	builder.AddNote("Generated by HyperSDK Nutanix pickup from Prism NFS mounts")
	builder.AddNote("Source disks converted with qemu-img for h2kvm pipeline consumption")

	for i, disk := range disks {
		if disk.OutputPath == "" {
			return nil, fmt.Errorf("disk %q missing output path", disk.UUID)
		}
		if _, err := os.Stat(disk.OutputPath); err != nil {
			return nil, fmt.Errorf("converted disk not found %q: %w", disk.OutputPath, err)
		}

		diskType := "data"
		if i == 0 {
			diskType = "boot"
		}

		bytes := disk.Bytes
		if bytes == 0 && disk.SizeGiB > 0 {
			bytes = int64(disk.SizeGiB * 1024 * 1024 * 1024)
		}

		builder.AddDisk(fmt.Sprintf("disk-%d", i), format, disk.OutputPath, bytes, i, diskType)
	}

	artifact, err := builder.Build()
	if err != nil {
		return nil, err
	}

	for i, disk := range disks {
		if i < len(artifact.Disks) && disk.DiskAddress != "" {
			artifact.Disks[i].Label = disk.DiskAddress
		}
	}

	return artifact, nil
}

// ParseMountMap parses mount specifications like "container-name:/mnt/ctr".
func ParseMountMap(specs []string) (MountMap, error) {
	m := make(MountMap)
	for _, spec := range specs {
		spec = strings.TrimSpace(spec)
		if spec == "" {
			continue
		}
		parts := strings.SplitN(spec, ":", 2)
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return nil, fmt.Errorf("invalid mount spec %q (expected name:/path)", spec)
		}
		m[parts[0]] = parts[1]
	}
	if len(m) == 0 {
		return nil, fmt.Errorf("at least one mount spec is required")
	}
	return m, nil
}
