apiVersion: v1
entries:
  transiva:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 0.2.0
    created: "2026-01-30T20:49:22.168026929+05:30"
    description: Multi-cloud VM migration platform for Kubernetes
    digest: 6840f2c84bb3ce5936e277a0bbd696fcf37cee9d0829dcbe36fbdb41fa0478bd
    home: https://github.com/zyvorai/transiva
    icon: https://raw.githubusercontent.com/ssahani/transiva/main/docs/images/logo.png
    keywords:
    - vm-migration
    - multi-cloud
    - vsphere
    - kubernetes
    - backup
    - disaster-recovery
    maintainers:
    - email: ssahani@zyvor.dev
      name: ZyvorAI Labs Private Limited
    name: transiva
    sources:
    - https://github.com/zyvorai/transiva
    type: application
    urls:
    - https://ssahani.github.io/transiva/helm-charts/transiva-0.2.0.tgz
    version: 0.2.0
generated: "2026-01-30T20:49:22.164233472+05:30"
