// SPDX-License-Identifier: Apache-2.0

package completion

// BashCompletion generates bash completion script
func BashCompletion() string {
	return `#!/bin/bash
# hyperctl bash completion script
# Generated by hyperctl completion bash

_hyperctl_completion() {
    local cur prev words cword
    _init_completion || return

    local commands="submit query list grep rg vm status cancel migrate interactive help completion version"

    # Flags for each command
    local submit_flags="-file -vm -output"
    local query_flags="-all -id -status"
    local list_flags="-json -filter"
    local grep_flags="-E -i -v -c -l -f -json"
    local rg_flags="-S -i -v -c -count-matches -l -files-without-match -color -stats -U -m -json"
    local vm_flags="-op -path -timeout"
    local cancel_flags="-id"
    local migrate_flags="-output -convert -import"
    local completion_flags="-shell"

    # Global flags
    local global_flags="-daemon -version"

    # If we're completing the first argument (command)
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$commands $global_flags" -- "$cur"))
        return 0
    fi

    # Get the command (first argument after hyperctl)
    local command="${words[1]}"

    case "$command" in
        submit)
            case "$prev" in
                -file)
                    _filedir '@(json|yaml|yml)'
                    return 0
                    ;;
                -vm|-output)
                    _filedir -d
                    return 0
                    ;;
                *)
                    COMPREPLY=($(compgen -W "$submit_flags $global_flags" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        query)
            case "$prev" in
                -status)
                    COMPREPLY=($(compgen -W "running completed failed cancelled pending" -- "$cur"))
                    return 0
                    ;;
                *)
                    COMPREPLY=($(compgen -W "$query_flags $global_flags" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        list)
            COMPREPLY=($(compgen -W "$list_flags $global_flags" -- "$cur"))
            return 0
            ;;
        grep)
            case "$prev" in
                -f)
                    COMPREPLY=($(compgen -W "name path os power all" -- "$cur"))
                    return 0
                    ;;
                *)
                    COMPREPLY=($(compgen -W "$grep_flags $global_flags" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        rg)
            case "$prev" in
                -color)
                    COMPREPLY=($(compgen -W "auto always never" -- "$cur"))
                    return 0
                    ;;
                *)
                    COMPREPLY=($(compgen -W "$rg_flags $global_flags" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        vm)
            case "$prev" in
                -op)
                    COMPREPLY=($(compgen -W "shutdown poweroff remove-cdrom info" -- "$cur"))
                    return 0
                    ;;
                -path)
                    # Could potentially complete VM paths from daemon in future
                    return 0
                    ;;
                *)
                    COMPREPLY=($(compgen -W "$vm_flags $global_flags" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        status)
            COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            return 0
            ;;
        cancel)
            COMPREPLY=($(compgen -W "$cancel_flags $global_flags" -- "$cur"))
            return 0
            ;;
        migrate|interactive)
            case "$prev" in
                -output)
                    _filedir -d
                    return 0
                    ;;
                -convert|-import)
                    COMPREPLY=($(compgen -W "true false" -- "$cur"))
                    return 0
                    ;;
                *)
                    COMPREPLY=($(compgen -W "$migrate_flags $global_flags" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        completion)
            case "$prev" in
                -shell)
                    COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
                    return 0
                    ;;
                *)
                    COMPREPLY=($(compgen -W "$completion_flags" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        help)
            # Complete with available commands
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
            return 0
            ;;
    esac

    return 0
}

complete -F _hyperctl_completion hyperctl
`
}
