// SPDX-License-Identifier: Apache-2.0

package completion

// FishCompletion generates fish completion script
func FishCompletion() string {
	return `# hyperctl fish completion script
# Generated by hyperctl completion fish

# Disable file completions for hyperctl
complete -c hyperctl -f

# Global flags
complete -c hyperctl -l daemon -d 'Daemon URL' -r
complete -c hyperctl -l version -d 'Show version'

# Commands
complete -c hyperctl -n '__fish_use_subcommand' -a submit -d 'Submit export job'
complete -c hyperctl -n '__fish_use_subcommand' -a query -d 'Query job status'
complete -c hyperctl -n '__fish_use_subcommand' -a list -d 'List VMs from vCenter'
complete -c hyperctl -n '__fish_use_subcommand' -a grep -d 'Search VMs (grep-like)'
complete -c hyperctl -n '__fish_use_subcommand' -a rg -d 'Advanced search (ripgrep-like)'
complete -c hyperctl -n '__fish_use_subcommand' -a vm -d 'VM operations'
complete -c hyperctl -n '__fish_use_subcommand' -a status -d 'Show daemon status'
complete -c hyperctl -n '__fish_use_subcommand' -a cancel -d 'Cancel running jobs'
complete -c hyperctl -n '__fish_use_subcommand' -a migrate -d 'Interactive VM migration'
complete -c hyperctl -n '__fish_use_subcommand' -a interactive -d 'Interactive VM migration'
complete -c hyperctl -n '__fish_use_subcommand' -a help -d 'Show help message'
complete -c hyperctl -n '__fish_use_subcommand' -a completion -d 'Generate shell completion'
complete -c hyperctl -n '__fish_use_subcommand' -a version -d 'Show version'

# submit command
complete -c hyperctl -n '__fish_seen_subcommand_from submit' -s f -l file -d 'Job file (JSON/YAML)' -F
complete -c hyperctl -n '__fish_seen_subcommand_from submit' -l vm -d 'VM path' -r
complete -c hyperctl -n '__fish_seen_subcommand_from submit' -l output -d 'Output directory' -r -a '(__fish_complete_directories)'

# query command
complete -c hyperctl -n '__fish_seen_subcommand_from query' -l all -d 'Query all jobs'
complete -c hyperctl -n '__fish_seen_subcommand_from query' -l id -d 'Query specific job ID' -r
complete -c hyperctl -n '__fish_seen_subcommand_from query' -l status -d 'Filter by status' -r -a 'running completed failed cancelled pending'

# list command
complete -c hyperctl -n '__fish_seen_subcommand_from list' -l json -d 'Output in JSON format'
complete -c hyperctl -n '__fish_seen_subcommand_from list' -l filter -d 'Filter VMs by name' -r

# grep command
complete -c hyperctl -n '__fish_seen_subcommand_from grep' -s E -d 'Use extended regex'
complete -c hyperctl -n '__fish_seen_subcommand_from grep' -s i -d 'Case-insensitive'
complete -c hyperctl -n '__fish_seen_subcommand_from grep' -s v -d 'Invert match'
complete -c hyperctl -n '__fish_seen_subcommand_from grep' -s c -d 'Count matches'
complete -c hyperctl -n '__fish_seen_subcommand_from grep' -s l -d 'List names only'
complete -c hyperctl -n '__fish_seen_subcommand_from grep' -s f -d 'Field to search' -r -a 'name path os power all'
complete -c hyperctl -n '__fish_seen_subcommand_from grep' -l json -d 'JSON output'

# rg command
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -s S -d 'Smart case'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -s i -d 'Case-insensitive'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -s v -d 'Invert match'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -s c -d 'Count matching VMs'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -l count-matches -d 'Count all matches'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -s l -d 'List names only'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -l files-without-match -d 'List non-matching VMs'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -l color -d 'Colorize output' -r -a 'auto always never'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -l stats -d 'Show statistics'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -s U -d 'Multiline matching'
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -s m -d 'Max matches' -r
complete -c hyperctl -n '__fish_seen_subcommand_from rg' -l json -d 'JSON output'

# vm command
complete -c hyperctl -n '__fish_seen_subcommand_from vm' -l op -d 'Operation' -r -a 'shutdown poweroff remove-cdrom info'
complete -c hyperctl -n '__fish_seen_subcommand_from vm' -l path -d 'VM path' -r
complete -c hyperctl -n '__fish_seen_subcommand_from vm' -l timeout -d 'Timeout in seconds' -r

# cancel command
complete -c hyperctl -n '__fish_seen_subcommand_from cancel' -l id -d 'Job ID to cancel' -r

# migrate command
complete -c hyperctl -n '__fish_seen_subcommand_from migrate' -l output -d 'Output directory' -r -a '(__fish_complete_directories)'
complete -c hyperctl -n '__fish_seen_subcommand_from migrate' -l convert -d 'Auto-convert to qcow2' -r -a 'true false'
complete -c hyperctl -n '__fish_seen_subcommand_from migrate' -l import -d 'Auto-import to libvirt' -r -a 'true false'

# interactive command (same as migrate)
complete -c hyperctl -n '__fish_seen_subcommand_from interactive' -l output -d 'Output directory' -r -a '(__fish_complete_directories)'
complete -c hyperctl -n '__fish_seen_subcommand_from interactive' -l convert -d 'Auto-convert to qcow2' -r -a 'true false'
complete -c hyperctl -n '__fish_seen_subcommand_from interactive' -l import -d 'Auto-import to libvirt' -r -a 'true false'

# completion command
complete -c hyperctl -n '__fish_seen_subcommand_from completion' -l shell -d 'Shell type' -r -a 'bash zsh fish'
`
}
