// SPDX-License-Identifier: Apache-2.0

package completion

// ZshCompletion generates zsh completion script
func ZshCompletion() string {
	return `#compdef hyperctl
# hyperctl zsh completion script
# Generated by hyperctl completion zsh

_hyperctl() {
    local -a commands
    commands=(
        'submit:Submit export job'
        'query:Query job status'
        'list:List VMs from vCenter'
        'grep:Search VMs (grep-like)'
        'rg:Advanced search (ripgrep-like)'
        'vm:VM operations (shutdown, poweroff, etc)'
        'status:Show daemon status'
        'cancel:Cancel running jobs'
        'migrate:Interactive VM migration'
        'interactive:Interactive VM migration (alias)'
        'help:Show help message'
        'completion:Generate shell completion script'
        'version:Show version information'
    )

    local -a global_flags
    global_flags=(
        '-daemon[Daemon URL]:url:_urls'
        '-version[Show version]'
    )

    _arguments -C \
        '1: :->cmds' \
        '*:: :->args' && return 0

    case "$state" in
        cmds)
            _describe -t commands 'hyperctl commands' commands
            _describe -t flags 'global flags' global_flags
            ;;
        args)
            case "$words[1]" in
                submit)
                    _arguments \
                        '-file[Job file (JSON/YAML)]:file:_files -g "*.{json,yaml,yml}"' \
                        '-vm[VM path]:path:_directories' \
                        '-output[Output directory]:dir:_directories' \
                        $global_flags
                    ;;
                query)
                    _arguments \
                        '-all[Query all jobs]' \
                        '-id[Query specific job ID]:id:' \
                        '-status[Filter by status]:status:(running completed failed cancelled pending)' \
                        $global_flags
                    ;;
                list)
                    _arguments \
                        '-json[Output in JSON format]' \
                        '-filter[Filter VMs by name]:filter:' \
                        $global_flags
                    ;;
                grep)
                    _arguments \
                        '-E[Use extended regular expressions]' \
                        '-i[Case-insensitive matching]' \
                        '-v[Invert match]' \
                        '-c[Count matching VMs]' \
                        '-l[List VM names only]' \
                        '-f[Field to search]:field:(name path os power all)' \
                        '-json[Output in JSON format]' \
                        '1:pattern:' \
                        $global_flags
                    ;;
                rg)
                    _arguments \
                        '-S[Smart case]' \
                        '-i[Case-insensitive]' \
                        '-v[Invert match]' \
                        '-c[Count matching VMs]' \
                        '-count-matches[Count individual matches]' \
                        '-l[List VM names only]' \
                        '-files-without-match[List VMs without match]' \
                        '-color[Colorize output]:color:(auto always never)' \
                        '-stats[Show search statistics]' \
                        '-U[Enable multiline matching]' \
                        '-m[Stop after N matches]:count:' \
                        '-json[Output in JSON format]' \
                        '*:pattern:' \
                        $global_flags
                    ;;
                vm)
                    _arguments \
                        '-op[Operation]:operation:(shutdown poweroff remove-cdrom info)' \
                        '-path[VM path]:path:' \
                        '-timeout[Timeout in seconds]:timeout:' \
                        $global_flags
                    ;;
                status)
                    _arguments $global_flags
                    ;;
                cancel)
                    _arguments \
                        '-id[Job ID to cancel]:id:' \
                        $global_flags
                    ;;
                migrate|interactive)
                    _arguments \
                        '-output[Output directory]:dir:_directories' \
                        '-convert[Auto-convert VMDK to qcow2]:bool:(true false)' \
                        '-import[Auto-import to libvirt]:bool:(true false)' \
                        $global_flags
                    ;;
                completion)
                    _arguments \
                        '-shell[Shell type]:shell:(bash zsh fish)' \
                        $global_flags
                    ;;
                help)
                    _describe -t commands 'hyperctl commands' commands
                    ;;
            esac
            ;;
    esac

    return 0
}

_hyperctl "$@"
`
}
